spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://localhost:15432/oneos?currentSchema=TASKDB
    username: postgres
    password: Postgres2022!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # sรณ durante o dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE